version: '3'

services:

  xonotic_server:
    build: .
    image: xonotic/xonotic:v1
    container_name: xonotic_server
    restart: unless-stopped
    volumes:
      - ./server.cfg:/Xonotic/data/server.cfg:rw
    ports:
      - 26000:26000/udp
